- name: Create Xml File
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/jenkins-test.xml

- name: Create Jenkins Job
  community.general.jenkins_job:
    config:  "{{ lookup('file', '/tmp/jenkins-test.xml') }}"
    name: "{{item.job_name}}"
    password: roboshop123
    url: http://172.31.12.82:8080
    user: roboshop
  